services: 
  grafana:
    image: grafana/grafana:latest
    ports: 
      - '3000:3000'
    networks: 
      - loki-net

  loki:
    image: grafana/loki:latest
    ports: 
      - '3100:3100'
    networks: 
      - loki-net
      
  database: 
    image: db_hakaton
    build:
      context: .
    ports:
      - "8000:8000"
    networks: 
      - loki-net
    depends_on:
      - grafana
      - loki
      - postgres
  
  postgres: 
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: pivan
      POSTGRES_PASSWORD: pivan1234
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - loki-net

volumes:
  postgres_data:
    
networks:
  loki-net:
    driver: bridge


